### PR TITLE
Set ceiling of threshold to 120 mg/dL

### PR DESCRIPTION
**Pull request by MikePlante1**
Currently, if you set your threshold above the max allowed 120 it will just ignore your setting and use the default. This would instead just reduce it to the maximum allowed 120.

### CODE REVIEW

**Comment by MikePlante1** [comment]
Please take into consideration that I don't know how to test this, since I don't know the process for converting to minified and adding to the iAPS code.

**Comment by Jon-b-m** [comment]
Thanks, Mike. You can test the code before PR:ing like this: 
[Change source code in Oref0.pdf](https://github.com/Artificial-Pancreas/oref2/files/13947192/Change.source.code.in.Oref0.pdf)

But I think we could simplify the code to just: 

profile.threshold_setting = min(max(threshold, 65), 120);
console.error("Threshold set to " + convert_bg(profile.threshold_setting, profile);

**Comment by Jon-b-m** [comment]
This is how I would write it:


// Use the configurable threshold setting
    if (profile.threshold_setting != 65) {
        threshold = Math.min(Math.max(profile.threshold_setting, 65), 120);
    } else {
        // Deafault OpenAPS threshold, which depends on current target glucose
        // min_bg of 90 -> threshold of 65, 100 -> 70 110 -> 75, and 130 -> 85
    threshold = min_bg - 0.5*(min_bg-40);
    }
    console.error("Threshold set to " + convert_bg(threshold, profile));

**Comment by Jon-b-m** [comment]
Above code is tested

**Comment by MikePlante1** [comment]
Ah cool, thanks for the tip on how to test it.

Your refactor looks great, but I'm not sure we should switch to using 65 for the floor rather. I think I would rather keep using the default threshold as the floor. I'm not super opposed to it or anything, just pointing out that it's weakening the current safety limit.

**Comment by Jon-b-m** [comment]
Do you mean making the customized setting just raising the minimum threshold, instead of as now setting a fixed threshold? That would be quite different from now.

**Comment by MikePlante1** [comment]
The way it looks to work right now (without this PR) is it sets the default threshold based on that formula using your targetBG, which if your targetBG is 130 your defaultThreshold would be 85. Then it uses this if statement `(th_setting > threshold && th_setting <= 120 && th_setting >= 65)` to ensure that the thresholdSetting that the user wants to set is within 65-120 as well as greater than the defaultThreshold. The problem with the current implementation is that if someone wants to be super conservative and sets their thresholdSetting above 120 then the code ignores their thesholdSetting and uses the default which is going to be a lot more aggressive. My PR's intent was just to make it so setting your thresholdSetting above the max allowed 120 brings it down to 120 and not the defaultThreshold.

Your suggesting would ensure their thresholdSetting is within 65-120, but only use the defaultThreshold if they leave (or set) thresholdSetting to the default 65, allowing someone to set a threshold of 66 with a targetBG of 130, whereas the old code would have restricted their thresholdSetting 85-120 with a targetBG of 130.

**Comment by Jon-b-m** [comment]
The old oref2 code if set to 66 would use 66 always (fixed setting). The original oref0 threshold was not designed to be configured. It was designed to set a safe threshold based on current target. If being configurable (and not to a fixed setting) it gets a bit difficult explaining. If we should make it, as you're suggesting?(which I'm not opposed to), non-fixed we need to rename it and change the description. Perhaps "minimum threshold setting"?

**Comment by MikePlante1** [comment]
Good call, I'll update the PR today to use the min/max functions after I use your instructions to test it, and if accepted I'll do a PR to the iAPS repo with the minified js as well as change the name to "minimum threshold". The tooltip isn't visible right now anyway, but I'll look to see if that needs updating as well and include it in the iAPS PR.

**Comment by Jon-b-m** [comment]
Please don't PR minimized code, as I can verify it. Oref2 code will suffice.

**Comment by MikePlante1** [comment]
Understood, that makes sense. I'll leave the minified out of the iAPS repo PR.

**Comment by MikePlante1** [comment]
Ran into problems with the web pack so I didn't test it yet. Going to try to figure that out again tomorrow.

**Comment by Jon-b-m** [comment]
It looks good now. Now we just need to explain to users the new threshold setting in docs, explaining what before was a fixed setting (when changed) is now dynamic. If you PR to docs I can minimize and merge this with iAPS.

**Comment by MikePlante1** [comment]
I just tested the latest dev in a simulator. I set target glucose to 135 mg/dL, toggled dynISF on, and set threshold to 66. The log confirms that threshold was set to 88 (the default calculated threshold from 135) and not the user set 66.

So the only thing this PR does (other than refactoring and simplifying the log entry) is reduce user-set thresholds to 120 when they exceed that maximum.

Here's the current tooltip in dev (even though none of the tooltips are visible in the dynISF menu). It does need to be updated, and I'll take care of it but not because of this PR.

"The default threshold in FAX depends on your current minimum BG target, as follows:

If your minimum BG target = 90 mg/dl -> threshold = 65 mg/dl,

if minimum BG target = 100 mg/dl -> threshold = 70 mg/dl,

minimum BG target = 110 mg/dl -> threshold = 75 mg/dl,

and if minimum BG target = 130 mg/dl  -> threshold = 85 mg/dl.

This setting allows you to change the default to a higher threshold for looping with dynISF. Valid values are 65 mg/dl<= Threshold Setting <= 120 mg/dl."

**Comment by MikePlante1** [comment]
I'm going to close this PR and open a new one so it's just one commit instead of 5. I did finally figure out what I was doing wrong with the webpack so I'll be able to test any oref2 changes before PRing them in the future.

**Comment by MikePlante1** [comment]
I'm going to close this PR and open a new one so it's just one commit instead of 5. I did finally figure out what I was doing wrong with the webpack so I'll be able to test any oref2 changes before PRing them in the future.

**Pull request merged**
